<?php require 'header.php'; ?>

	<!-- Content AUP -->
	<div class="container content-md aup">
		<p><h1 class="pull-left">Acceptable Use Policy</h1></p>
		<h3 class="lb">Background</h3>
		<p>This "Acceptable Use Policy" or "AUP" of YOP Cloud, Inc., a Quebec corporation in Canada, and all other divisions and identities used by YOP Cloud, Inc. and references herein after to YOP Cloud includes reference to the foregoing terms. This AUP is designed to provide a clear understanding of the rules, regulations, and restrictions on the use of the Services, Servers, and IP Addresses of YOP Cloud Inc. YOP Cloud Inc., from time to time at the sole discretion of YOP Cloud Inc., impose rules, regulations, or restrictions not expressly stated in this AUP on the use of the Services, Servers, and IP Addresses of YOP Cloud Inc. may, from time to time at the sole discretion of YOP Cloud Inc., modify this AUP and such modification shall become immediately effective upon posting of the modified AUP to <a href="http://www.yopcloud.com/aup">http://www.yopcloud.com/AUP</a>or by notification to you of the modified AUP. This AUP is not exhaustive. Hereinafter, "Services" is defined as any offering of YOP Cloud Inc. including, without limitation, those managed, in whole or in part, for you by YOP Cloud Inc., "Servers" is defined as any CPU based hardware platform of YOP Cloud Inc. including, without limitation, those managed, in whole or in part, for you by YOP Cloud Inc., and "IP Addresses" is defined as any publicly routable IPv4 32-bit or IPv6 128-bit Internet Protocol address assigned by YOP Cloud Inc. to you as part of the Services or Servers provided to you by YOP Cloud Inc.. By registering for or using the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc., you accept and agree to abide by the terms and conditions of the "Terms of Service" or "TOS" of YOP Cloud Inc., the rules, regulations, and restrictions of the "Acceptable Use Policy" or "AUP" of YOP Cloud Inc., the "End User Content Policy" or "EUCP" of YOP Cloud Inc.and the laws of the cities, states, and countries wherein the Services, Servers, or IP Addresses of YOP Cloud Inc.are located which are hereby incorporated into this AUP. Solicitation of any illegal act on, to, from, or through the Services, Servers, or IP addresses provided to you by YOP Cloud Inc., whether performed or not, is a violation of this AUP.</p>
		<h3 class="lb">SUSPENSION AND CANCELLATION</h3>
		<p>NONPAYMENT IN WHOLE OR IN PART FOR ANY OF THE SERVICES, SERVERS, OR IP ADDRESSES PROVIDED TO YOU BY YOP Cloud INC.OR VIOLATION OF THE ACCEPTABLE USE POLICY OF YOP Cloud INC., THE ACCEPTABLE USE POLICY OF ANY UPSTREAM PROVIDER OF YOP Cloud INC., OR THE ACCEPTABLE USE POLICY OF ANY NETWORK CONNECTED ON, TO, FROM, OR THROUGH THE SERVICES, SERVERS, OR IP ADDRESSES PROVIDED TO YOU BY YOP Cloud INC.MAY, AT THE SOLE DISCRETION OF YOP Cloud INC., RESULT IN THE IMMEDIATE SUSPENSION OR CANCELLATION OF ANY OR ALL SERVICES, SERVERS, OR IP ADDRESSES PROVIDED TO YOU BY YOP Cloud INC.OR OTHER ACTION DEEMED APPROPRIATE BY YOP Cloud INC.WITHOUT REMUNERATION FOR SUCH SUSPENSION, CANCELLATION, OR OTHER ACTION OR ASSURANCE OF PRIOR NOTIFICATION TO YOU FOR SUCH SUSPENSION, CANCELLATION, OR OTHER ACTION AND ANY FEES PAID IN ADVANCE OF SUCH SUSPENSION, CANCELLATION, OR OTHER ACTION ARE NON-REFUNDABLE.</p>
		<h3 class="lb">INDEMNIFICATION</h3>
		<p>YOU ACKNOWLEDGE YOUR INDEMNIFICATION OBLIGATIONS UNDER THE TERMS OF SERVICE OF YOP Cloud INC.AND AGREE THAT YOU ARE SOLELY LIABLE AND RESPONSIBLE FOR ANY AND ALL MONETARY DAMAGES RESULTING DIRECTLY OR INDIRECTLY FROM VIOLATIONS OF THIS AUP TO INCLUDE, WITHOUT LIMITATION, THE SERVICES, SERVERS, AND IP ADDRESSES PROVIDED TO YOU BY YOP Cloud INC., THE NETWORK AND BUSINESS OPERATIONS OF YOP Cloud INC., RELATED COSTS INCURRED BY YOP Cloud INC., AND ANY THIRD PERSON OR PARTY AND THAT SUCH MONETARY DAMAGES WILL BE CHARGED TO YOUR ACCOUNT. VIOLATIONS OF THIS AUP MAY RESULT IN SIGNIFICANT CIVIL AND CRIMINAL LIABILITY TO YOU.</p>
		<h3 class="lb">DATA LIABILITY AND RESPONSIBILITY</h3>
		<p>YOU ARE SOLELY LIABLE AND RESPONSIBLE FOR ANY AND ALL DATA STORED OR TRANSMITTED ON, TO, FROM, OR THROUGH THE SERVICES, SERVERS, AND IP ADDRESSES PROVIDED TO YOU BY YOP Cloud INC.TO INCLUDE, WITHOUT LIMITATION, BLOCK SPECIAL FILES, CHARACTER SPECIAL FILES, DIRECTORIES, SYMBOLIC LINKS, SOCKET LINKS, FIFOS, REGULAR FILES, PROGRAMS, DATABASES, TEXT, GRAPHICS, PICTURES, MOVIES, AUDIO, STREAMING MEDIA, WEB PAGES, HYPERLINKS, EMAIL, INSTANT MESSAGES, CHAT MESSAGES, FILE TRANSFERS, HOST NAMES, AND DOMAIN NAMES.</p>
		<h3 class="lb">DISCLAIMER OF RESPONSIBILITY</h3>
		<p>YOP Cloud INC.ASSUMES NO LIABILITY OR RESPONSIBILITY TO ANY PERSON OR PARTY FOR ANY VIOLATION OF THIS AUP BY ANY OTHER PERSON OR PARTY. IT IS THE POLICY OF YOP Cloud INC., BUT NOT ITS OBLIGATION, TO MONITOR ITS NETWORK FOR POTENTIAL, ALLEGED, OR ACTUAL VIOLATIONS OF THIS AUP AND TO CANCEL EGREGIOUS OR REPEAT OFFENDERS OF THIS AUP WITHOUT PRIOR NOTICE.</p>
		<h3 class="lb">SUBJUGATION</h3>
		<p>ALL RESELLERS, CLIENTS, USERS, AND SUB NETWORKS OF THE SERVICES, SERVERS, AND IP ADDRESSES PROVIDED BY YOP Cloud INC. ARE SUBJECT TO THIS AUP AND ANY ATTEMPTED OR ACTUAL VIOLATION OF THIS AUP BY ANY PERSON OR PARTY ON YOUR BEHALF SHALL BE A VIOLATION OF THIS AUP BY YOU.</p>
		<h3 class="lb">PROSECUTION AND FINES</h3>
		<p>YOP Cloud INC. COOPERATES FULLY WITH LAW ENFORCEMENT AGENCIES IN THE INVESTIGATION AND PROSECUTION OF CRIMINAL ACTIVITY AND HAS ZERO TOLERANCE FOR VIOLATIONS OF THIS AUP. WE RESERVE THE RIGHT TO LEVY FINES OF $500 TO $5000 USD PER INCIDENT FOR ANY VIOLATION OF THIS AUP.</p>
		<h3 class="lb">RIGHT OF REFUSAL</h3>
		<p>YOP Cloud INC. RESERVES THE RIGHT TO REFUSE SERVICE TO ANYONE AT ANY TIME.</p>
		<h3 class="lb">Policy Enforcement and Resolution</h3>
		<p>Violations of this AUP are, at the sole discretion of YOP Cloud Inc., enforced by issuance of a Policy Enforcement notice to the registered contact email addresses of the Services, Servers, or IP Addresses and, additionally, may be issued to the registered abuse contact email addresses of the Services, Servers, or IP Addresses. It is your responsibility to request from <a href="mailto:abuse@yopcloud.com">abuse@yopcloud.com</a> abuse contact email addresses. Failure to receive a Policy Enforcement notice does not limit the right of enforcement by YOP Cloud Inc. of this AUP or your responsibility to resolve violations of this AUP in a manner acceptable to YOP Cloud Inc.. You must remove all domains, sites, users, or exploits causing a violation of this AUP from the Services, Servers, and IP Addresses of YOP Cloud Inc.. You must reconfigure, harden, or remove any improperly configured or insecure software causing a violation of this AUP. However, YOP Cloud Inc. may, at the sole discretion of YOP Cloud Inc., access any managed Server or Service of YOP Cloud Inc. or require root access to any self-managed Server or Service of YOP Cloud Inc. to remove the cause of an abuse or reconfigure, harden, or remove any improperly configured or insecure software. You must reply to the Policy Enforcement notice within the time frame given in the notice with appropriate comments, questions, or actions to resolve the violations cited in the notice. Depending on the violation type, severity, history, quantity of complaints, upstream provider requirements, and other factors, your Services, Servers, or IP Addresses may be: Monitored for Additional Violations<br /> Disconnected, Null-Routed, or Port Shutdown in 24-Hours, 16-Hours, 8-Hours, 1-Hour, or 0-Hours as Indicated<br /> Required to Provide root Login Information for our Direct Investigation, Cleaning, Hardening, and/or Securing<br /> Required to Submit Reload Ticket With or Without Data Recovery as Indicated<br /> Required to Remove Current End-User-Client from All Servers<br /> Placed on 30-Day Probation<br /> Reviewed for Probation Violation<br /> Hard Drives Seized<br /> Cancelled</p>
		<h3 class="lb">Specific Violations of This AUP Without Limitation</h3>
		<p>The following hour groupings are the standard times provided for an initial reply from the client with appropriate comments, questions, or actions to resolve the abuse issue indicated in a Policy Enforcement notice to prevent suspension of services, servers, or IP addresses. These times are not a guarantee and may be modified on a case-by-case basis depending on the abuse type, severity, history, quantity of complaints, upstream provider requirements, and other factors.</p>
		<p><span style="text-decoration: underline;">24-HOUR ISSUES:</span></p>
		<p><strong>Copyright</strong><br /> Hosting, Distributing, or Linking to Copyright Infringed Materials.<br /> See <a href="http://www.copyright.gov/title17/92chap5.html" target="_blank">http://www.copyright.gov/title17/92chap5.html</a></p>
		<p><strong>Embargo</strong><br /> Hosting or Linking to a Site Prohibited by Embargo.<br /> See <a href="http://www.yopcloud.com/embargo" target="_blank">http://www.yopcloud.com/embargo</a></p>
		<p><strong>Forgery</strong><br /> Faking an IP Address, Hostname, E-Mail Address, or Header.</p>
		<p><strong>Invalid Hostname</strong><br /> A vain, obscene, or malicious host or domain name.</p>
		<p><strong>IRC Unregistered</strong><br /> Internet Relay Chat Server not Registered and Approved by YOP Cloud Inc. abuse department.</p>
		<p><strong>Pharmaceuticals</strong><br /> Hosting, Distributing, or Linking to Pharmaceutical/Drug Sites.</p>
		<p><strong>Shells</strong><br /> Hosting Accounts Primarily for Shell Access.</p>
		<p><strong>Spam Email</strong><br /> Unsolicited Bulk Email (UBE).</p>
		<p><strong>Spam News</strong><br /> Posting the same message repeatedly in one or more newsgroups or posting an off-topic message to a newsgroup.</p>
		<p><strong>Spam Site</strong><br /> Hosting a Site Advertised by Spam Email, Spam News, or Spam Web.</p>
		<p><strong>Spam Web</strong><br /> Unsolicited, Bulk, or Forged Site Advertisement in Web Logs, Forums, or Guest books.</p>
		<p><strong>Tools</strong><br /> Hosting, Distributing, or Linking to Cracking, DoS, Forgery, Infection, or Scanning Software or Instruction.</p>
		<p><strong>Trademark</strong><br /> Hosting, Distributing, or Linking to Trade Mark Infringed Materials.</p>
		<p><strong>Wares</strong><br /> Hosting, Distributing, or Linking to Cracks, Hacks, Key Generators, Serials, or Pirated Software.</p>
		<p><span style="text-decoration: underline;">16-HOUR ISSUES:</span></p>
		<p><strong>Advance Fee Fraud</strong><br /> Spam to Solicit an Advance Fee in Return for Monetary Gain.</p>
		<p><strong>HYIP Site</strong><br /> Hosting or Linking to a Website of High Yield Investment Program, Ponzi Scheme, or Pyramid Scheme.</p>
		<p><strong>Infection</strong><br /> Hosting, Distributing, or Linking to Exploits, Trojans, Viruses, or Worms.</p>
		<p><strong>IRC Malicious</strong><br /> Malicious Use of Internet Relay Chat.</p>
		<p><strong>Scanning</strong><br /> Probing for Vulnerabilities of Network Devices.</p>
		<p><strong>SORBS</strong><br /> SORBS blacklisting at <a href="http://www.sorbs.net" target="_blank">http://www.sorbs.net</a> of an IP.</p>
		<p><strong>Spam List</strong><br /> Hosting, Distributing, or Linking to Email Address Lists for Spam.</p>
		<p><strong>Spam Ware</strong><br /> Hosting, Distributing, or Linking to Software Designed for Spamming.</p>
		<p><strong>Spamhaus</strong><br /> Spamhaus Blacklisting at <a href="http://www.spamhaus.org" target="_blank">http://www.spamhaus.org</a> of an IP.</p>
		<p><strong>Web Spider</strong><br /> Use of a Web Spider, Crawler, or Bot for Unauthorized Connection to 3rd Party Web Servers.</p>
		<p><span style="text-decoration: underline;">8-HOUR ISSUES:</span></p>
		<p><strong>Child Porn Link</strong><br /> Linking to Content of Pornography Involving a Person Under Legal Age. See 18 USC Chapter 110 Sections 2256 and 2257 <a href="http://uscode.house.gov/download/pls/18C110.txt" target="_blank">http://uscode.house.gov/download/pls/18C110.txt</a></p>
		<p><strong>Cracking</strong><br /> Brute Force Access of Secured Network Devices.</p>
		<p><strong>DoS</strong><br /> Denial of Service Attack of Network Devices.</p>
		<p><strong>Fraud Site</strong><br /> Hosting or Linking to a Website Intended to Deceive the Public.</p>
		<p><strong>Hacking</strong><br /> Circumventing Security Systems of Network Devices.</p>
		<p><strong>ID Theft</strong><br /> Hosting, Distributing, or Linking to Stolen Account Identification Information.</p>
		<p><strong>Open Proxy</strong><br /> Hosting an Open Proxy.</p>
		<p><strong>Open Relay</strong><br /> Hosting an Open Relay.</p>
		<p><strong>Phishing</strong><br /> Identity Theft by Email Under False Pretense.</p>
		<p><strong>Proxy Hijack</strong><br /> Use of a Third Party Proxy Vulnerability or Trojan.</p>
		<p><strong>Terrorist Site</strong><br /> Hosting or Linking to a Site Advocating Terrorism.<br /> See <a href="http://www.treas.gov/offices/enforcement/ofac/programs/terror/terror.pdf" target="_blank">http://www.treas.gov/offices/enforcement/ofac/programs/terror/terror.pdf</a></p>
		<p><span style="text-decoration: underline;">1-HOUR ISSUES:</span></p>
		<p><strong>Child Porn Dist</strong><br /> Distributing Content of Pornography Involving a Person Under Legal Age. See 18 USC Chapter 110 Sections 2256 and 2257 <a href="http://uscode.house.gov/download/pls/18C110.txt" target="_blank">http://uscode.house.gov/download/pls/18C110.txt</a></p>
		<p><strong>ROKSO</strong><br /> ROKSO Blacklisting at <a href="http://www.spamhaus.org" target="_blank">http://www.spamhaus.org</a> of an IP.<br /> See <a href="http://www.spamhaus.org/rokso/index.lasso" target="_blank">http://www.spamhaus.org/rokso/index.lasso</a></p>
		<p><strong>Upstream AUP</strong><br /> Violation of AUP of an Upstream Provider of YOP Cloud Inc.</p>
		<p><span style="text-decoration: underline;">0-HOUR ISSUES:</span></p>
		<p><strong>Child Porn Host</strong><br /> Hosting Content of Pornography Involving a Person Under Legal Age. See 18 USC Chapter 110 Sections 2256 and 2257 <a href="http://uscode.house.gov/download/pls/18C110.txt" target="_blank">http://uscode.house.gov/download/pls/18C110.txt</a></p>
		<h3 class="lb">Self-Managed and Partially-Managed Services, Servers, and IP Addresses</h3>
		<p>With respect to self-managed and partially-managed Services, Servers, and IP Addresses provided to you by YOP Cloud Inc., you are solely responsible, without limitation, for the management, administration, and security of the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc., for any and all data stored or transmitted on, to, from, or through the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc., and for all passwords provided to you by YOP Cloud Inc.. Should it become necessary for YOP Cloud Inc. to perform, at your request, any management, administration, or security work on the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc. to resolve a violation of this AUP in a manner acceptable to YOP Cloud Inc., which includes DEFCON 4 and 5 management, administration, and security work, you agree to pay YOP Cloud Inc. $150.00 USD per hour one-hour minimum.</p>
		<h3 class="lb nmt">Fully-Managed Services, Servers, and IP Addresses</h3>
		<p>With respect to fully-managed Services, Servers, and IP Addresses provided to you by YOP Cloud Inc., you are solely responsible, without limitation, for any and all data stored or transmitted on, to, from, or through the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc. and for all passwords provided to you by YOP Cloud Inc.. YOP Cloud Inc. are responsible for the management, administration, and security of the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc.. Should it become necessary for YOP Cloud Inc. to perform any management, administration, or security work on the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc. to resolve a violation of this AUP in a manner acceptable to YOP Cloud Inc., which includes DEFCON 3, 2, and 1 management, administration, and security work, you agree that YOP Cloud Inc. may perform such management, administration, or security work without prior approval and you agree to pay YOP Cloud Inc. $150.00 USD per hour one-hour minimum for any management, administration, or security work performed in excess of your allocated "Advanced Administration" hours.</p>
		<h3 class="lb">Contact Information</h3>
		<p>You are responsible for maintaining your contact information in the ticket system such that your registered contact email address is always reachable even in the event of disconnection of the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc..</p>
		<h3 class="lb">IP Address Overlap</h3>
		<p>Use of a publicly routable IP address not provided to you by YOP Cloud Inc. on the Services or Servers provided to you by YOP Cloud Inc. is a violation of this AUP.</p>
		<h3 class="lb">Network Performance</h3>
		<p>YOP Cloud Inc. provides shared network resources and, therefore, excessive use or abuse of these shared network resources by one client of YOP Cloud Inc. may adversely affect other clients of YOP Cloud Inc. or the network of YOP Cloud Inc.. Any misuse of network resources in a manner which may adversely affect other clients of YOP Cloud Inc. or the network of YOP Cloud Inc. is a violation of this AUP.</p>
		<h3 class="lb">Internet Etiquette</h3>
		<p>You and all users of the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc. are expected to practice good Internet etiquette (Netiquette). Any activity or data stored or transmitted on, to, from, or through the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc., whether legal or not, which may adversely affect other clients of YOP Cloud Inc., the network of YOP Cloud Inc. as a result of an offended third person or party, or the reputation of YOP Cloud Inc. is a violation of this AUP.</p>
		<h3 class="lb nmt">Definition of SPAM</h3>
		<p>All Unsolicited Bulk Email or "UBE", email which is both unsolicited and bulk, is hereby defined in this AUP as spam. Unsolicited means the recipient did not give verifiable, deliberate, explicit, and revocable permission for the message to be sent. Bulk means the message was sent to multiple recipients with substantively identical content and, therefore, the recipient's personal identity and context are irrelevant because the email is equally applicable to multiple recipients. Spam is an issue of consent, not content. No other definition of spam including, without limitation, Title 15 USC Chapter 103 Controlling the Assault of Non-Solicited Pornography and Marketing § 7702 et. al or "CAN-SPAM Act" applies to the definition of spam as used in this AUP.</p>
		<h3 class="lb nmt">Opt-In Mailing Lists</h3>
		<p>Mailing lists must be true opt-in which requires you to provide to the recipient either a confirmation email or a confirmation web page whereby the recipient must have replied with a confirmation email having a unique tracking number or must have clicked a hyperlink in the confirmation email having a unique tracking number maintained in your web server log file or must have clicked the hyperlink in the confirmation web page having a unique tracking number maintained in your web server log file thereby granting verifiable, deliberate, explicit, and revocable permission to be added to the specific opt-in email list at the specific site both of which must be hosted on the network of YOP Cloud Inc. and under your administrative control. You are required to provide the confirmation email reply with unique tracking number or the web server log file line having the unique tracking number as evidence that the recipient did, indeed, opt-in to the email list. You are also required to provide at least one simple method to opt out of the email list which must be honored immediately.</p>
		<h3 class="lb">Free Hosting Services</h3>
		<p>You are liable and responsible for violations of this AUP by all third persons or parties for whom you provide free web, mail, ftp, or other hosting. YOP Cloud Inc. strongly advise you not to provide free hosting to unknown provided to you by YOP Cloud Inc. occurs resulting from such free hosting, YOP Cloud Inc. may, at the sole discretion of YOP Cloud Inc., suspend or cancel any or all Services, Servers, and IP Addresses provided to you by YOP Cloud Inc. or require you to remove such free hosting from the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc..</p>
		<h3 class="lb nmt">TOR and Anonymous Routers or Routing Protocols</h3>
		<p>If an alleged or actual violation of this AUP is believed, at the sole discretion of YOP Cloud Inc., to have occurred on, to, from, or through the Services, Servers, or IP Addresses provided to you by YOP Cloud Inc. on which TOR or an anonymous router or routing protocol exists, the alleged or actual violation of this AUP shall be deemed to have occurred whether verifiable evidence exists or not and YOP Cloud Inc. shall enforce this AUP at the sole discretion of YOP Cloud Inc..</p>
		<h3 class="lb nmt">Bit Torrent, Point-to-Point, and Proxy Software</h3>
		<p>Bit Torrent, Point-to-Point, and Proxy software are permitted until and unless abuse occurs related to such software. Should abuse occur related to such software, YOP Cloud Inc. may, at the sole discretion of YOP Cloud Inc., require removal of such software from the Services, Servers, and IP Addresses of YOP Cloud Inc..</p>
		<h3 class="lb">Billing</h3>
		<p>You are responsible for paying for any network resources used to connect the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc. to the Internet. Pursuant to the Terms of Service of YOP Cloud Inc., you may request that the Services, Servers, and IP Addresses provided to you by YOP Cloud Inc. be disconnected from the Internet. However, you remain responsible for paying for any network resources used up to the time of disconnection.</p>
		<h3 class="lb">Governing Law and Jurisdiction</h3>
		<p>This Agreement is governed by the laws of the province of Québec and the laws of Canada applicable therein. The Parties irrevocably submit all disputes arising out of this Agreement to Québec courts, judicial district of Montréal 
		<p></p> 
		<p>Violations of this AUP should be reported to <a href="mailto:abuse@yopcloud.com">abuse@yopcloud.com</a></p>
		<p></br></p>
	</div>
	<!-- End of AUP -->
	
<?php require 'footer.php';	?>