<?php require 'header.php'; ?>
	
	<!-- Content TOS -->
	<div class="container content-md tos">
		<p><h1 class="pull-left">Terms of Service (TOS)</h1></p>
		<h3>Appellation</h3>
		<p>This YOP Cloud inc. Terms of Service (this "Agreement") and the YOP Cloud inc. Acceptable Use Policy ("AUP") govern your purchase and use of all YOP Cloud inc. services (collectively, the "Services"), as described in the Order Form(s) submitted by you and accepted by YOP Cloud inc. ("Service Order"). Acceptance of any terms or conditions different from those contained herein by YOP Cloud inc. will not be deemed by provision of service, but only by electronic or written signature of an officer of YOP Cloud inc.. You must register and accept the terms of this Agreement and the AUP in order to use the Services. BY CHECKING THE "I ACCEPT" CHECKBUTTON IN AN ORDER, AND/OR REGISTERING FOR AND USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS AGREEMENT AND THE AUP, AND AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS OF THIS AGREEMENT AS WELL AS ALL POLICIES AND GUIDELINES OF THE AUP, WHICH ARE INCORPORATED HEREIN BY REFERENCE. YOP Cloud inc. may modify any of the terms and conditions contained in this Agreement and the AUP, at any time, in its sole discretion. Any modifications are effective upon posting of the revisions on the YOP Cloud inc. web site (the "Site"). Your continued use of the Services following YOP Cloud inc. posting of any modifications constitutes your acceptance of the modifications. If you do not agree to the terms of any modification, do not continue to use the services and immediately notify YOP Cloud inc. of your termination of this Agreement in the manner described in the section below. YOP Cloud inc. agrees to furnish services to the Subscriber, subject to the following TOS (Terms of Service). The Use of YOP Cloud inc. service constitutes acceptance and agreement to YOP Cloud inc. AUP as well as YOP Cloud inc. TOS (Terms of Service).</p>
		<h3>Term and Payment for Services</h3>
		<p>Term: This Agreement will be for an initial "Term" of 1 month from the date the Services are first provided by YOP Cloud inc.. This Agreement will be automatically renewed (the "Renewal Term") at the end of the Initial Term or any Renewal Term for a period of thirty (30) days unless you provide YOP Cloud inc. with written notice of termination at least two days (2) before the end of the Initial Term or Renewal Term (also referred to interchangeably and collectively as "Term"), whichever is then applicable. To provide your notice of termination, you must login to your billing account and submit a ticket to the Billing department via <a href="http://billing.yopcloud.com/index.php?/tickets/new/">http://billing.yopcloud.com/index.php?/tickets/new/</a>and fill out the corresponding cancellation information required to initiate the cancellation of your service. Pricing and duration of Terms may be modified only if in writing (such as a Service Order) signed by YOP Cloud inc.</p>
		<h3 class="nmt">Termination</h3>
		<p>This Agreement may be terminated: (i) by you or YOP Cloud inc. during any Renewal Term, without cause, by giving the other party no less than two (2) days prior written notice, or a greater number of days prior notice if specified in a Service Order accepted by YOP Cloud inc.; (ii) by YOP Cloud inc. in the event of nonpayment by you as provided in the section below or (iii) by YOP Cloud inc., at any time, without notice, if, in YOP Cloud inc. sole judgment, you are in violation of any terms or conditions of the AUP. If you terminate this Agreement, or if YOP Cloud inc. terminates this Agreement for your breach, before the end of the Initial Term or the Renewal Term, whichever is then applicable, you will be required to pay immediately and without setoff or delay all charges, fees and costs accrued before the termination date, all monthly recurring fees for each month remaining in the Term and any other amounts including, but not limited to, bandwidth overage charges that you owe to YOP Cloud inc. under this Agreement.</p>
		<h3 class="nmt">Charges</h3>
		<p>You will immediately pay, upon receiving an electronic invoice from YOP Cloud inc., all charges for your use of the Services at the then current YOP Cloud inc. prices for that category of service or any special offer applicable to your account as determined by YOP Cloud inc.. You are responsible for paying all federal, state, and local sales, use, value added, excise duty and any other taxes assessed with respect to the Services, other than taxes based on YOP Cloud inc. net income. If you are a resident of Texas, your purchase of dedicated hosting services is subject to the Texas sales tax rate of 8.25%. All setup fees are subject to an 8.25% tax. If you default on any of your obligations under this Agreement and YOP Cloud inc. must engage a collections effort to collect past due sums associated with your use of Services, you are responsible for all costs of collection of all amounts owed under this Agreement, including reasonable attorney's fees of YOP Cloud inc.. Your server comes with a set bandwidth allotment of 1000 GB for Tier 1 clients, 1200 GB for Tier 2 clients and 1500 GB for Tier 3. This represents the amount of bandwidth that you are allowed to use for each calendar month. If you exceed this allotment for any reason in any calendar month, even if you have cancelled service with YOP Cloud inc. during the month, you will be charged overage bandwidth at a rate of $.50 per gigabyte. Bandwidth billing is done in arrears, and you will receive your bill for overage bandwidth during the first week of the following month that the overage occurred. It is your responsibility to monitor your bandwidth usage and to pay for all overages. If you are a reseller, it is your responsibility to monitor the bandwidth usage of your client(s) as you are solely responsible for any and all overages incurred by them.</p>
		<h3 class="nmt">Payment and Fees</h3>
		<p>You will pay all charges for the first month of service in advance on the first day of the Initial Term. You will pay all subsequent charges for Services in their entirety in advance on the anniversary day of each successive month. You must pay for the Services by credit card or PayPal. You authorize YOP Cloud inc. to charge your credit or debit card to pay for any charges that may apply to your account. You have a specific obligation to immediately notify YOP Cloud inc. of any changes to your card account (including applicable account number or cancellation or expiration of the account, your billing address, or any information that may prohibit YOP Cloud inc. from properly charging your account). Failure to immediately and fully pay your fees for Services and applicable taxes when invoiced by YOP Cloud inc. shall be a material breach of this Agreement, justifying YOP Cloud inc .to suspend its performance and terminate this Agreement. If<br /> YOP Cloud inc. terminates this Agreement for your material breach, you will be required to pay immediately all fees and costs accrued before the termination date, all monthly recurring fees for each month remaining in the term and any other amounts you owe to YOP Cloud inc. under this Agreement including, but not limited to, bandwidth overage charges. You are responsible for any costs that YOP Cloud inc. incurs in enforcing collection, including reasonable attorneys' fees, court costs and collection agency fees. Credit cards that are declined for any reason or Paypal payments that are either rejected or not made when Services are invoiced are subject to an additional processing fee. Service will be immediately interrupted on any account that is unpaid. Service interrupted for non-payment is subject to a $25 suspension charge per server. Accounts not paid by the due date are subject to a $5 late fee that accrues daily until paid in full. Accounts that are not collectable by YOP Cloud inc. may be turned over to an outside collection agency for collection. If you account is turned over for collection, you agree to pay the company an additional "Collection" fee of not less than $50 nor more than $150. If you desire to cancel the account, please send an email to <a href="mailto:sales@yopcloud.com">sales@yopcloud.com</a>.</p>
		<h3 class="nmt">Refund and Disputes</h3>
		<p>*All payments to YOP Cloud inc. are nonrefundable* and include any applicable setup fees and subsequent charges regardless of usage. All overcharges or billing disputes must be reported within 60 days of the time that the dispute occurred. If you dispute a charge to your credit card issuer that, in YOP Cloud inc. sole discretion, is a valid charge under the provisions of this Agreement and/or AUP, you agree to pay<br />YOP Cloud inc. an additional "Investigation Fee" of $100.00.</p>
		<h3 class="nmt">Failure to Pay</h3>
		<p>The Company may temporarily deny service or terminate this Agreement upon the failure of Subscriber to pay charges when due. Such termination or denial will not, in any way, relieve the Subscriber of responsibility for the payment of all accrued charges, plus reasonable interest and all collection fees, including legal expenses.</p>
		<h3>Use of Services</h3>
		<p>Services. The AUP is posted on the site at (or such other location as YOP Cloud inc. may specify) and may be updated from time to time. BY USING THE SERVICES, YOU AGREE TO BE BOUND BY THE TERMS OF THE AUP AND ANY MODIFICATIONS TO THE TERMS. YOP Cloud INC.MAY TERMINATES YOUR ACCOUNT WITHOUT NOTICE FOR ANY VIOLATION OF THE AUP OR THIS AGREEMENT. Security: You are solely responsible for any security breaches affecting servers or accounts under your control. If your server is responsible for or involved in an attack on or unauthorized access into another server or system, YOP Cloud inc. will shut it down immediately. You will pay any charges resulting from the cost to correct security breaches affecting YOP Cloud inc. or any of its other customers.</p>
		<h3 class="nmt">System and Network Security</h3>
		<p>Users are prohibited from violating or attempting to violate the security of the YOP Cloud inc. proprietary network. Violations of system or network security may result in civil or criminal liability. YOP Cloud inc. will investigate occurrences which may involve, and cooperate with law enforcement authorities in prosecuting Users who are involved in such violations. These violations include, without limitation: Accessing data not intended for such user or logging into a server or account, which such user is not authorized to access.<br /> Attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization.<br /> Attempting to interfere with service to any user, host or network, including without limitation, via means of overloading, flooding, mail bombing or crashing.<br /> Forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting.<br /> Taking any action in order to obtain services which such user is not entitled.</p>
		<h3 class="nmt">Notification of Violations or Infractions</h3>
		<p>YOP Cloud inc. is under no duty to look at each client's or user's activities to determine if a violation of the AUP has occurred, nor do we assume any responsibility through our AUP to monitor or police Internet related activities.</p>
		<h3 class="nmt">Violations of the AUP will result in the following:</h3>
		<p>A warning notification sent via email, YOP Cloud inc. trouble ticket with 24 hours notice for resolution: 24 hours is the standard notification; situations involving law enforcement, phishing scams, fraud, password harvesting, network interference, Denial or Disruption of service, IRC related misuse, or other malicious activity can reduce the notification time frame. First Violation: Any user, which YOP Cloud inc. determines to have violated any element of our AUP (Acceptable use Policy), shall receive an e-mail, warning them of the violation. The service may be subject at YOP Cloud inc. discretion to a temporary suspension pending a client's agreement in writing to refrain from any further violations.<br /> Second Violation: Any client that YOP Cloud inc. determines to have committed a second violation of any element or portion of the AUP shall be subject to immediate suspension or termination of service without further notice.<br /> We reserve the right to drop the section of IP space involved in any SPAM or Denial-of-Service (Dos) complaints if it is clear that the offending activity is causing great harm to parties on the Internet. In particular, if open relays are on your network or a customer's network, or if denial-of-service attacks are originating from your network. In certain rare cases, we may have to take this action prior to attempting to contact you.</p>
		<h3 class="nmt">Disclosure to Law Enforcement</h3>
		<p>The AUP specifically prohibits the use of our service for illegal activities. Therefore, Subscriber agrees that the Company may disclose any and all Subscriber information, including assigned IP addresses, account history, account use, etc. to any law enforcement agency who makes a written request without further consent or notification to the Subscriber. In addition YOP Cloud inc. shall have the right to terminate all service set forth in this Agreement if requested to do so as a result of any action of any law enforcement or government agency.</p>
		<h3 class="nmt">Support Services and Boundaries</h3>
		<p>YOP Cloud inc.provides 24/7/365 technical support to our Subscribers. We limit our technical support to our area of expertise. The following are our guidelines when providing support: YOP Cloud inc. provides support related to your server. YOP Cloud inc. does not provide support for application specific issues, such as any programming, HTML, third party applications or any other such issue.<br /> YOP Cloud inc. does not provides technical support for YOUR clients.</p>
		<h3>Reseller Policy</h3>
		<p>Resellers are completely and entirely responsible for the conduct of their customers and by agreeing with this AUP, Resellers agree that their customers will adhere to the AUP. Resellers have an obligation under this Agreement to make their current and prospective customers aware of the AUP and the consequences of violation of same.</p>
		<h3 class="nmt">Intellectual Property Rights</h3>
		<p>Your Warranties and Representations to YOP Cloud inc.: You warrant, represent, and covenant to<br /> YOP Cloud inc. that: (a) you are at least 18 years of age if an individual; (b) you possess the legal right and ability to enter into this Agreement; (c) you will use the Services only for lawful purposes and in accordance with this Agreement and all applicable policies and guidelines, including the AUP; and (d) your content does not and will not infringe or violate any right of any third party (including any intellectual property rights) or violate any applicable law, regulation or ordinance. Intellectual Property Policy YOP Cloud inc. respects the intellectual property rights of others and expects its users to do the same. YOP Cloud inc. reserves the right, at its discretion, to delete material that infringes the copyrights, trademarks, or other intellectual property rights of others. YOP Cloud inc. also reserves the right to disable and/or terminate the accounts of users who infringe the copyrights, trademarks or other intellectual property rights of others. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide YOP Cloud inc. with the following information: A description of the copyrighted work property that you claim has been infringed;<br /> A description of the material that you claim infringes your copyright, and information sufficient to allow us to locate the material;<br /> Your address, telephone number, and e-mail address;<br /> A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;<br /> A statement by you, made under penalty of perjury, that the information provided is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf;<br /> An electronic or physical signature of a person authorized to act on behalf of the owner of the copyright.</p>
		<h3 class="nmt">IP Addresses</h3>
		<p>YOP Cloud inc. will maintain and control ownership of all Internet Protocol ("IP") numbers and addresses that YOP Cloud inc. may assign to you. YOP Cloud inc. may, in its sole discretion, change or remove any and all IP numbers and addresses at any time.</p>
		<h3>Third Party Products</h3>
		<p>YOP Cloud inc. may provide you with access to other third party software and/or services ("Third Party Products") through reseller relationships that YOP Cloud inc. has established with certain commercial vendors, including without limitation, Microsoft Corporation ("Third Party Vendors"). Unless otherwise notified, Customer understands that product support for Third Party Products is provided by YOP Cloud inc. and not by the Third Party Vendor. Neither YOP Cloud inc. nor any Third Party Vendor makes any representations or warranties, expressed or implied, regarding any Third Party Products. CUSTOMER EXPRESSLY ACKNOWLEDGES AND AGREES THAT USE OF THIRD PARTY PRODUCTS IS AT CUSTOMER'S SOLE RISK AND SUCH THIRD PARTY PRODUCTS ARE PROVIDED "AS IS" AND WITHOUT REPRESENTATION OR WARRANTY OF ANY KIND FROM YOP Cloud inc. OR ANY THIRD PARTY VENDOR, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS OF RESPONSES OR RESULTS, CORRESPONDENCE TO DESCRIPTION, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEITHER YOP Cloud inc. NOR ANY THIRD PARTY VENDOR WILL BE LEGALLY RESPONSIBLE FOR ANY DAMAGES, WHETHER DIRECT, INDIRECT, OR CONSEQUENTIAL, ARISING FROM THE USE OR INABILITY TO USE ANY THIRD PARTY PRODUCT. CUSTOMER AGREES TO OBSERVE THE TERMS OF ANY LICENSE AND/OR APPLICABLE END USER SUBSCRIBER AGREEMENT FOR THIRD PARTY PRODUCTS AND THAT CUSTOMER SHALL BE FULLY LIABLE TO THIRD PARTY VENDORS AND YOP Cloud inc. WITH RESPECT TO ANY IMPROPER USE OF SUCH THIRD PARTY PRODUCTS OR VIOLATION OF LICENSE AGREEMENTS WITH THEM AND/OR APPLICABLE END USER SUBSCRIBER AGREEMENTS. You shall not (i) remove, modify or obscure any copyright, trademark or other proprietary rights notices that appear on any Third Party Product or that appear during use of any Third Party Product; or (ii) reverse engineer, decompile, or disassemble any Third Party Product, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.</p>
		<h3>Enforcement Actions</h3>
		<p>YOP Cloud inc. reserves the right to suspend or terminate the Service immediately or take any other corrective action it deems appropriate in its sole discretion if, in the sole judgment of YOP Cloud inc., your server is the source or target of any violation of the AUP or for any other reason which YOP Cloud inc. reasonably chooses. If inappropriate activity is detected, all of your accounts in question will be deactivated until a thorough investigation is completed. Prior notification to you of disconnection is not assured. In some cases, law enforcement will be contacted regarding the activity. These rights of action, however, do not obligate YOP Cloud inc. to monitor or exert editorial control over the information made available for distribution via the Services. If YOP Cloud inc. takes corrective action because of a possible violation, YOP Cloud inc. will not refund you any fees that you paid in advance of the corrective action.</p>
		<h3 class="nmt">Disclosure Rights</h3>
		<p>The AUP specifically prohibits the use of our service for illegal activities. Therefore, you agree that YOP Cloud inc. may disclose any and all of your information including assigned IP numbers, account history, account use, etc. to any law enforcement agent who makes a written request without further consent or notification to you. In addition, YOP Cloud inc. shall have the right to terminate all service set forth in this Agreement.</p>
		<h3 class="nmt">Disclaimed Warranties</h3>
		<p>YOP Cloud inc. exercises no control over, and accepts no responsibility for, the content of the information passing through YOP Cloud inc. host computers, network hubs and points of presence, or the Internet. USE OF THE SERVICES OR ANY INFORMATION THAT MAY BE OBTAINED THEREFROM IS AT YOUR OWN RISK. ALL SERVICES PERFORMED UNDER THIS AGREEMENT ARE PERFORMED "AS IS" AND WITHOUT WARRANTY AGAINST FAILURE OF PERFORMANCE INCLUDING, ANY FAILURE BECAUSE OF COMPUTER HARDWARE OR COMMUNICATION SYSTEMS. YOP Cloud INC.DOES NOT MAKE AND DISCLAIMS, AND YOU WAIVE ALL RELIANCE ON, ANY REPRESENTATIONS OR WARRANTIES, ARISING BY LAW OR OTHERWISE, REGARDING THE SERVICES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE IN TRADE. YOP Cloud INC.DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.</p>
		<h3 class="lb">Limitation and Exclusion of Liability</h3>
		<h3 class="nmt">Limitations</h3>
		<p>IN NO EVENT WILL YOP Cloud INC.OR ITS SUPPLIERS HAVE ANY LIABILITY FOR UNAUTHORIZED ACCESS TO, OR ALTERATION, THEFT OR DESTRUCTION OF INFORMATION DISTRIBUTED OR MADE AVAILABLE FOR DISTRIBUTION VIA THE SERVICES THROUGH ACCIDENT, FRAUDULENT MEANS OR DEVICES. NEITHER YOP Cloud INC.NOR ITS SUPPLIERS WILL HAVE LIABILITY WITH RESPECT TO YOP Cloud INC.NOLOGIES' OBLIGATIONS UNDER THIS AGREEMENT, OR OTHERWISE FOR CONSEQUENTIAL, EXEMPLARY, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES EVEN IF YOP Cloud INC.HAS BEEN ADVISED OF THE POSSIBILITY OF THESE DAMAGES. THE LIABILITY OF YOP Cloud INC.AND ITS SUPPLIERS TO YOU FOR ANY REASON AND UPON ANY CAUSE OF ACTION IS LIMITED TO THE AMOUNT YOU ACTUALLY PAID TO YOP Cloud INC.UNDER THIS AGREEMENT DURING THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE DATE ON WHICH THE CLAIM ACCRUED. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION IN THE AGGREGATE, INCLUDING BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATIONS, AND OTHER TORTS. THE FEES FOR THE SERVICES SET BY YOP Cloud INC.UNDER THIS AGREEMENT HAVE BEEN AND WILL CONTINUE TO BE BASED UPON THIS ALLOCATION OF RISK. ACCORDINGLY, YOU RELEASE YOP Cloud INC.AND ITS SUPPLIERS FROM ANY AND ALL OBLIGATIONS, LIABILITIES, AND CLAIMS IN EXCESS OF THE LIMITATION STATED IN THIS SECTION.</p>
		<h3 class="nmt">Interruption of Service</h3>
		<p>YOP Cloud inc. and its suppliers are not liable for any temporary delay, outages or interruptions of the Services. Further, YOP Cloud inc. is not liable for any delay or failure to perform its obligations under this Agreement, where the delay or failure results from any "act of God" or other cause beyond its reasonable control (including any mechanical, electronic, communications or third-party supplier failure).</p>
		<h3 class="nmt">Indemnification</h3>
		<p>In agreeing to the YOP Cloud inc.AUP and this Agreement, you agree to indemnify, defend and hold harmless YOP Cloud inc., its employees, officers, directors, partners, representatives and affiliates, for any violation by you or your customers of the AUP or this Agreement that results either in (a) any cost, expense, damage or loss to YOP Cloud inc., or (b) the bringing of any claim against YOP Cloud inc. by any third-party, and all costs, expenses, damages, and losses associated therewith. For example, if YOP Cloud inc. is being sued because of your or your customer's activity related to the Services, you will pay any damages awarded against YOP Cloud inc., its employees, directors, partners, representatives and affiliates, in addition to all costs and attorney's fees.</p>
		<h3>MISCELLANEOUS PROVISIONS</h3>
		<p>YOP Cloud inc. and you agree that, except as otherwise expressly provided in this Agreement, the Order Form(s) or the terms and conditions of use of any third party software products, there shall be no third party beneficiaries to this Agreement, including but not limited to the insurance providers for either party or your customers. THIS AGREEMENT IS MADE UNDER AND WILL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF TEXAS (EXCEPT THAT BODY OF LAW CONTROLLING CONFLICTS OF LAW) AND SPECIFICALLY EXCLUDING FROM APPLICATION TO THIS AGREEMENT THAT LAW KNOWN AS THE UNITED NATIONS CONVENTION ON THE INTERNATIONAL SALE OF GOODS. EXCLUSIVE VENUE FOR ALL DISPUTES ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL BE THE STATE AND FEDERAL COURTS IN TEXAS, AND EACH PARTY IRREVOCABLY CONSENTS TO SUCH PERSONAL JURISDICTION AND WAIVES ALL OBJECTIONS THERETO. In the event any provision of this Agreement is held by a tribunal of competent jurisdiction to be contrary to the law, the remaining provisions of this Agreement will remain in full force and effect. The waiver of any breach or default of this Agreement will not constitute a waiver of any subsequent breach or default, and will not act to amend or negate the rights of the waiving party. You may not sell, assign or transfer its rights or delegate its duties under this Agreement either in whole or in part without the prior written consent of YOP Cloud inc., and any attempted assignment or delegation without such consent will be void. YOP Cloud inc. may assign this Agreement in whole or part. YOP Cloud inc. also may delegate the performance of certain Services to third parties. All notices, demands, requests or other communications required or permitted under this Agreement shall be deemed given when delivered personally, sent by facsimile upon confirmation, sent and received by return receipt email, or upon receipt of delivery of overnight mail. You and YOP Cloud inc. are independent contractors and this Agreement will not establish any relationship of partnership, joint venture, employment, franchise or agency between you and YOP Cloud inc.. This Agreement, including all documents incorporated herein by reference, constitutes the complete and exclusive agreement between the parties with respect to the subject matter hereof, and supersedes and replaces any and all prior or contemporaneous discussions, negotiations, understandings and agreements, written and oral, regarding such subject matter.</p>
		<h3>Survival</h3>
		<p>All provisions of this Agreement relating to your warranties, intellectual property rights, limitation and exclusion of liability, your indemnification obligations and payment obligations will survive the termination or expiration of the Agreement.</p>
		<h3>Governing Law and Jurisdiction</h3>
		<p>This Agreement is governed by the laws of the province of Québec and the laws of Canada applicable therein. The Parties irrevocably submit all disputes arising out of this Agreement to Québec courts, judicial district of Montréal</p>
		<p></br></p>
	</div>
	<!-- END Content TOS -->
	
	
<?php require 'footer.php';	?>